{
 "title": "AppGear Monitor (Availability)",
 "tags": [
  "kubernetes",
  "appgear"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "LiteLLM Instances Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{app=\"litellm\"})",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "Kubernetes Nodes Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{job=\"kubernetes-nodes\"})",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "All AppGear Pods Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "up{kubernetes_namespace=\"appgear\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}