apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appgear-modulos-v0-3
  namespace: argocd
spec:
  generators:
    - list:
        elements:
- id: M00
  name: fundamentos
  path: gitops/apps/m00-fundamentos
- id: M01
  name: gitops-argo
  path: gitops/apps/m01-gitops-argo
- id: M02
  name: borda
  path: gitops/apps/m02-borda
- id: M03
  name: observabilidade
  path: gitops/apps/m03-observabilidade
- id: M04
  name: bancos-core
  path: gitops/apps/m04-bancos-core
- id: M05
  name: seguranca-segredos
  path: gitops/apps/m05-seguranca-segredos
- id: M06
  name: identidade-sso
  path: gitops/apps/m06-identidade-sso
- id: M07
  name: portal-backstage
  path: gitops/apps/m07-portal-backstage
- id: M08
  name: apps-core
  path: gitops/apps/m08-apps-core
- id: M09
  name: suite-factory
  path: gitops/apps/m09-factory
- id: M10
  name: suite-brain
  path: gitops/apps/m10-brain
- id: M11
  name: suite-operations
  path: gitops/apps/m11-operations
- id: M12
  name: suite-guardian
  path: gitops/apps/m12-guardian
- id: M13
  name: workspaces-vcluster
  path: gitops/apps/m13-workspaces-vcluster
- id: M14
  name: pipelines-ai-first
  path: gitops/apps/m14-pipelines-ai-first
- id: M15
  name: dr-backup
  path: gitops/apps/m15-dr-backup
- id: M16
  name: conectividade-hibrida
  path: gitops/apps/m16-conectividade-hibrida
- id: M17
  name: politicas-operacionais
  path: gitops/apps/m17-politicas-operacionais

template:
  metadata:
    name: "appgear-{{id | lower}}-{{name}}"
    labels:
      appgear.io/module-id: "{{id}}"
      appgear.io/module-name: "{{name}}"
  spec:
    project: core
    source:
      repoURL: git@github.com:psstz-lima/AppGear.git  # TODO: ajuste para o repo real
      targetRevision: main
      path: "{{path}}"
    destination:
      server: https://kubernetes.default.svc
      namespace: appgear-core
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
